// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjhpjcmwuqnixvvannjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqaHBqY213dXFuaXh2dmFubmp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTQ1ODYsImV4cCI6MjA2MzQzMDU4Nn0.5QjLgxIoY5FqPmF2lu_GiLVC2X2UxwgM_RoQRL54HlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);